'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { supabaseBrowser } from '@/lib/supabase'

export default function Admin(){
 const sb=supabaseBrowser(); const [email,setEmail]=useState('ayushmourya590@gmail.com'); const [sent,setSent]=useState(false); const [user,setUser]=useState<any>(null); const [products,setProducts]=useState<any[]>([]); const [form,setForm]=useState({name:'',affiliate_url:'',image_url:'',price:'',category_id:'',why_picked:'',published:false}); const [msg,setMsg]=useState('')
 useEffect(()=>{sb.auth.getUser().then(({data})=>setUser(data.user)); sb.auth.onAuthStateChange((_e,s)=>setUser(s?.user??null))},[])
 async function login(){setMsg('');const {error}=await sb.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.origin+'/admin'}});setMsg(error?.message||'Magic link sent. Check your email.') ;setSent(!error)}
 async function load(){const {data}=await sb.from('products').select('*').order('created_at',{ascending:false});setProducts(data||[])}
 useEffect(()=>{if(user?.email==='ayushmourya590@gmail.com')load()},[user])
 async function add(){setMsg('');if(!form.name||!form.affiliate_url){setMsg('Name and affiliate URL are required.');return}const slug=form.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')+'-'+Date.now().toString().slice(-5);const {error}=await sb.from('products').insert({name:form.name,slug,affiliate_url:form.affiliate_url,image_url:form.image_url||null,price:form.price?Number(form.price):null,category_id:form.category_id||null,why_picked:form.why_picked||null,published:form.published,store:'Amazon'});setMsg(error?.message||'Product saved.');if(!error){setForm({name:'',affiliate_url:'',image_url:'',price:'',category_id:'',why_picked:'',published:false});load()}}
 if(!user)return <main className="admin"><div className="container"><div className="adminpanel" style={{maxWidth:480,margin:'10vh auto'}}><Link className="brand" href="/">AYUSH<span style={{color:'var(--accent)'}}>PICKS</span></Link><h1>Admin access</h1><p className="muted small">Private dashboard for AYUSHPICKS. Sign in with the owner email.</p><div className="field"><label>Email</label><input value={email} onChange={e=>setEmail(e.target.value)} type="email"/></div><button className="btn primary" style={{marginTop:12,width:'100%'}} onClick={login}>{sent?'Link sent':'Send magic link'}</button>{msg&&<p className="status">{msg}</p>}</div></div></main>
 return <main className="admin"><div className="container"><div className="adminbar"><div><Link className="brand" href="/">AYUSH<span style={{color:'var(--accent)'}}>PICKS</span></Link><div className="muted small">Admin dashboard</div></div><button className="btn" onClick={()=>sb.auth.signOut()}>Sign out</button></div>{user.email!=='ayushmourya590@gmail.com'?<div className="notice">This account is not authorized as the AYUSHPICKS admin.</div>:<div className="formgrid"><section className="adminpanel"><h2>Add product</h2><p className="muted small">Paste the Amazon affiliate URL. Automatic marketplace importing can be added later when an approved product-data source is available.</p><div className="form"><div className="field"><label>Product name</label><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="field"><label>Affiliate URL</label><input value={form.affiliate_url} onChange={e=>setForm({...form,affiliate_url:e.target.value})}/></div><div className="field"><label>Image URL</label><input value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})}/></div><div className="field"><label>Price (INR)</label><input value={form.price} onChange={e=>setForm({...form,price:e.target.value})} inputMode="decimal"/></div><div className="field"><label>Why we picked it</label><textarea value={form.why_picked} onChange={e=>setForm({...form,why_picked:e.target.value})}/></div><label className="small"><input type="checkbox" checked={form.published} onChange={e=>setForm({...form,published:e.target.checked})}/> Publish immediately</label><button className="btn primary" onClick={add}>Save product</button>{msg&&<div className="status">{msg}</div>}</div></section><section className="adminpanel"><h2>Products</h2><div className="productlist">{products.map(p=><div className="productrow" key={p.id}><div className="rowinfo"><strong>{p.name}</strong><span className="muted small">{p.published?'Published':'Draft'} · {p.store}</span></div></div>)}{!products.length&&<div className="empty">No products yet.</div>}</div></section></div>}</div></main>
}