'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { supabaseBrowser } from '@/lib/supabase'
import { ADMIN_EMAIL } from '@/lib/config'

const initialForm = { name:'', affiliate_url:'', image_url:'', price:'', old_price:'', category_id:'', short_description:'', why_picked:'', published:false, featured:false }

export default function Admin(){
  const sb = supabaseBrowser()
  const [email,setEmail]=useState(ADMIN_EMAIL)
  const [sent,setSent]=useState(false)
  const [user,setUser]=useState<any>(null)
  const [products,setProducts]=useState<any[]>([])
  const [categories,setCategories]=useState<any[]>([])
  const [form,setForm]=useState(initialForm)
  const [editing,setEditing]=useState<string|null>(null)
  const [msg,setMsg]=useState('')
  const [busy,setBusy]=useState(false)

  useEffect(()=>{sb.auth.getUser().then(({data})=>setUser(data.user));const {data:sub}=sb.auth.onAuthStateChange((_e,s)=>setUser(s?.user??null));return()=>sub.subscription.unsubscribe()},[])
  useEffect(()=>{if(user?.email===ADMIN_EMAIL){load();sb.from('categories').select('*').order('name').then(({data})=>setCategories(data||[]))}},[user])
  async function login(){setBusy(true);setMsg('');const {error}=await sb.auth.signInWithOtp({email:email.trim(),options:{emailRedirectTo:window.location.origin+'/admin'}});setMsg(error?.message||'Magic link sent. Check your email.');setSent(!error);setBusy(false)}
  async function load(){const {data}=await sb.from('products').select('*').order('created_at',{ascending:false});setProducts(data||[])}
  function slugify(v:string){return v.toLowerCase().normalize('NFKD').replace(/[^a-z0-9\s-]/g,'').trim().replace(/[\s_-]+/g,'-').replace(/^-+|-+$/g,'')}
  function startEdit(p:any){setEditing(p.id);setForm({name:p.name||'',affiliate_url:p.affiliate_url||'',image_url:p.image_url||'',price:p.price?.toString()||'',old_price:p.old_price?.toString()||'',category_id:p.category_id||'',short_description:p.short_description||'',why_picked:p.why_picked||'',published:!!p.published,featured:!!p.featured});window.scrollTo({top:0,behavior:'smooth'})}
  function reset(){setEditing(null);setForm(initialForm);setMsg('')}
  async function save(){setMsg('');if(!form.name.trim()||!form.affiliate_url.trim()){setMsg('Product name and affiliate URL are required.');return}setBusy(true);const payload={name:form.name.trim(),slug:slugify(form.name)+'-'+Date.now().toString().slice(-6),affiliate_url:form.affiliate_url.trim(),image_url:form.image_url.trim()||null,price:form.price?Number(form.price):null,old_price:form.old_price?Number(form.old_price):null,category_id:form.category_id||null,short_description:form.short_description.trim()||null,why_picked:form.why_picked.trim()||null,published:form.published,featured:form.featured,store:'Amazon'};const result=editing?await sb.from('products').update(payload).eq('id',editing):await sb.from('products').insert(payload);setMsg(result.error?.message|| (editing?'Product updated.':'Product added.'));if(!result.error){reset();await load()}setBusy(false)}
  async function remove(id:string){if(!confirm('Delete this product?'))return;setBusy(true);const {error}=await sb.from('products').delete().eq('id',id);setMsg(error?.message||'Product deleted.');await load();setBusy(false)}
  async function togglePublished(p:any){const {error}=await sb.from('products').update({published:!p.published}).eq('id',p.id);setMsg(error?.message||(p.published?'Moved to draft.':'Published.'));await load()}

  if(!user)return <main className="admin"><div className="container"><div className="adminpanel" style={{maxWidth:480,margin:'10vh auto'}}><Link className="brand" href="/">AYUSH<span>PICKS</span></Link><div className="eyebrow" style={{marginTop:22}}>PRIVATE ADMIN</div><h1>Sign in</h1><p className="muted small">Only the AYUSHPICKS owner account can manage products.</p><div className="field"><label>Email</label><input value={email} onChange={e=>setEmail(e.target.value)} type="email"/></div><button disabled={busy} className="btn primary" style={{marginTop:12,width:'100%'}} onClick={login}>{busy?'Sending…':sent?'Link sent':'Send magic link'}</button>{msg&&<p className="status">{msg}</p>}</div></div></main>
  if(user.email!==ADMIN_EMAIL)return <main className="admin"><div className="container"><div className="notice">This account is signed in, but it is not authorized to manage AYUSHPICKS.</div></div></main>
  return <main className="admin"><div className="container"><div className="adminbar"><div><Link className="brand" href="/">AYUSH<span>PICKS</span></Link><div className="muted small">Content dashboard</div></div><div style={{display:'flex',gap:8}}><Link className="btn" href="/">View site</Link><button className="btn" onClick={()=>sb.auth.signOut()}>Sign out</button></div></div>
    <div className="stats"><div className="adminpanel"><div className="muted small">TOTAL</div><strong>{products.length}</strong></div><div className="adminpanel"><div className="muted small">PUBLISHED</div><strong>{products.filter(p=>p.published).length}</strong></div><div className="adminpanel"><div className="muted small">CLICKS</div><strong>{products.reduce((n,p)=>n+Number(p.click_count||0),0)}</strong></div></div>
    <div className="formgrid"><section className="adminpanel"><div className="sectionhead"><div><h2>{editing?'Edit product':'Add product'}</h2><div className="muted small">Use your approved retailer / affiliate URL.</div></div>{editing&&<button className="btn" onClick={reset}>Cancel</button>}</div><div className="form"><div className="field"><label>Product name</label><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="e.g. OnePlus Nord Buds"/></div><div className="field"><label>Affiliate URL</label><input value={form.affiliate_url} onChange={e=>setForm({...form,affiliate_url:e.target.value})} placeholder="https://…"/></div><div className="field"><label>Image URL</label><input value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})} placeholder="https://…"/></div><div className="two"><div className="field"><label>Price (₹)</label><input value={form.price} onChange={e=>setForm({...form,price:e.target.value})} inputMode="decimal"/></div><div className="field"><label>Old price (₹)</label><input value={form.old_price} onChange={e=>setForm({...form,old_price:e.target.value})} inputMode="decimal"/></div></div><div className="field"><label>Category</label><select value={form.category_id} onChange={e=>setForm({...form,category_id:e.target.value})}><option value="">No category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label>Short description</label><textarea value={form.short_description} onChange={e=>setForm({...form,short_description:e.target.value})} placeholder="What this product is useful for…"/></div><div className="field"><label>Why we picked it</label><textarea value={form.why_picked} onChange={e=>setForm({...form,why_picked:e.target.value})} placeholder="Your original editorial reasoning…"/></div><div style={{display:'flex',gap:18,flexWrap:'wrap'}}><label className="small"><input type="checkbox" checked={form.published} onChange={e=>setForm({...form,published:e.target.checked})}/> Published</label><label className="small"><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Featured</label></div><button disabled={busy} className="btn primary" onClick={save}>{busy?'Saving…':editing?'Update product':'Add product'}</button>{msg&&<div className="status">{msg}</div>}</div></section>
    <section className="adminpanel"><div className="sectionhead"><div><h2>Products</h2><div className="muted small">Manage everything without touching GitHub.</div></div></div><div className="productlist">{products.map(p=><div className="productrow" key={p.id}><div className="rowinfo"><strong>{p.name}</strong><span className="muted small">{p.published?'Published':'Draft'} · {p.store||'Amazon'} · {Number(p.click_count||0)} clicks</span></div><div className="rowactions"><button className="btn" onClick={()=>startEdit(p)}>Edit</button><button className="btn" onClick={()=>togglePublished(p)}>{p.published?'Draft':'Publish'}</button><button className="btn danger" onClick={()=>remove(p.id)}>Delete</button></div></div>)}{!products.length&&<div className="empty">No products yet. Add your first pick.</div>}</div></section></div></div></main>
}
